version: '3.6'
services:
  postgres:
    image: mgorski/postgres-initial-db:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      postgres-backend:
        ipv4_address: "192.168.44.4"
networks:
  postgres-backend:
    driver: "bridge"
    ipam:
      config:
        - subnet: "192.168.44.0/24"
